# Makefile for gopy pkg generation of python bindings to pyexp
# File is generated by gopy (will not be overwritten though)
# gopy pkg -output=example -vm=python3 github.com/natun-ai/natun/pkg/pyexp

PYTHON ?= python3
PIP ?= $(PYTHON) -m pip
GOOS ?= $(shell go env GOOS)
EXT_PATH ?= build/_pyexp.so
GOEXT_PATH ?= build/pyexp_go.so

.PHONY: build-go
build-go:
	$(MAKE) -C pyexp build EXT_PATH="../$(EXT_PATH)" GOEXT_PATH="../$(GOEXT_PATH)"

.PHONY: build-wheel
build-wheel:
	$(PYTHON) -m build --wheel

.PHONY: build-repair
build-repair:
	$(eval WHEEL=$(shell ls -1t dist/*.whl | head -n1))
ifeq ($(shell go env GOOS), windows)
	@echo "skipping repair on windows..."
else ifeq ($(shell go env GOOS), darwin)
	delocate-listdeps $(WHEEL) &&  delocate-wheel --require-archs x86_64 -w repaired_wheel $(WHEEL)
else ifeq ($(shell go env GOOS), linux)
	auditwheel repair -w repaired_wheel $(WHEEL)
else
	@echo "Unknown OS: $(shell go env GOOS)"
endif

build-wheel2:
	echo "x"

.PHONY: cleanup
cleanup:
	make -C pyexp cleanup && rm -rf build/ dist/ natun_pysdk.egg-info/ .egg