# Makefile for gopy pkg generation of python bindings to pyexp
# File is generated by gopy (will not be overwritten though)
# gopy pkg -output=example -vm=python3 github.com/natun-ai/natun/pkg/pyexp

PYTHON ?= python

.PHONY: build-wheel
build-wheel:
	$(PYTHON) -m build --wheel

.PHONY: build-repair
build-repair:
	$(eval WHEEL=$(shell ls -1t dist/*.whl | head -n1))
ifeq ($(shell go env GOOS), windows)
	delvewheel repair --add-path natun/pyexp -w repaired_wheel $(WHEEL)
else ifeq ($(shell go env GOOS), darwin)
	delocate-listdeps $(WHEEL) &&  delocate-wheel -w repaired_wheel -v $(WHEEL)
else ifeq ($(shell go env GOOS), linux)
	auditwheel repair -w repaired_wheel $(WHEEL)
else
	@echo "Unknown OS: $(shell go env GOOS)"
endif

.PHONY: cleanup
cleanup:
	@echo "cleaning up..."
	rm -rf build/ dist/ natun_labsdk.egg-info/ .egg natun/pyexp repaired_wheel